name: mlgeo
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - jupyterlab
  - pyarrow
  - plotly
  - geopandas
  - matplotlib
  - numpy
  - scipy
  - pandas
  - rasterio
  - scikit-learn
  - shapely
  - netcdf4
  - wget
  - h5py
  - zarr
  - xarray
  - obspy
  - folium
  - seaborn
  - pytorch
  - torchvision
  - pip=20
  - pip:
    - pooch
